run:
  timeout: 5m
  modules-download-mode: vendor

linters:
  enable:
    - errcheck # Checks for unhandled errors
    - gosimple # Simplifies Go code
    - govet # Vet reports potential issues
    - staticcheck # Advanced static analysis
    - unused # Checks for unused variables/constants

issues:
  exclude-rules:
    # Exclude specific issues
    - path: configs/database/postgres/function.go
      linters:
        - staticcheck
    - path: pkg/logger/newrelic.go
      linters:
        - staticcheck
    - path: api/http/http.go
      linters:
        - errcheck
