// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fahmialfareza/deals-dating-app-backend/internal/repository/postgres (interfaces: IPostgresRepository,IUserPostgresRepository,ISwipePostgresRepository,IPurchasePostgresRepository)

// Package mocks_postgres_repository is a generated GoMock package.
package mocks_postgres_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/fahmialfareza/deals-dating-app-backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockIPostgresRepository is a mock of IPostgresRepository interface.
type MockIPostgresRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPostgresRepositoryMockRecorder
}

// MockIPostgresRepositoryMockRecorder is the mock recorder for MockIPostgresRepository.
type MockIPostgresRepositoryMockRecorder struct {
	mock *MockIPostgresRepository
}

// NewMockIPostgresRepository creates a new mock instance.
func NewMockIPostgresRepository(ctrl *gomock.Controller) *MockIPostgresRepository {
	mock := &MockIPostgresRepository{ctrl: ctrl}
	mock.recorder = &MockIPostgresRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPostgresRepository) EXPECT() *MockIPostgresRepositoryMockRecorder {
	return m.recorder
}

// GetSwipe mocks base method.
func (m *MockIPostgresRepository) GetSwipe(arg0 context.Context, arg1 uint, arg2 time.Time) ([]domain.Swipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwipe", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Swipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwipe indicates an expected call of GetSwipe.
func (mr *MockIPostgresRepositoryMockRecorder) GetSwipe(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwipe", reflect.TypeOf((*MockIPostgresRepository)(nil).GetSwipe), arg0, arg1, arg2)
}

// GetUserDetail mocks base method.
func (m *MockIPostgresRepository) GetUserDetail(arg0 context.Context, arg1 *uint, arg2 *string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDetail indicates an expected call of GetUserDetail.
func (mr *MockIPostgresRepositoryMockRecorder) GetUserDetail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDetail", reflect.TypeOf((*MockIPostgresRepository)(nil).GetUserDetail), arg0, arg1, arg2)
}

// GetUserProfile mocks base method.
func (m *MockIPostgresRepository) GetUserProfile(arg0 context.Context, arg1 []uint) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", arg0, arg1)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockIPostgresRepositoryMockRecorder) GetUserProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockIPostgresRepository)(nil).GetUserProfile), arg0, arg1)
}

// InsertPurchase mocks base method.
func (m *MockIPostgresRepository) InsertPurchase(arg0 context.Context, arg1 *domain.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPurchase", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPurchase indicates an expected call of InsertPurchase.
func (mr *MockIPostgresRepositoryMockRecorder) InsertPurchase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPurchase", reflect.TypeOf((*MockIPostgresRepository)(nil).InsertPurchase), arg0, arg1)
}

// InsertSwipe mocks base method.
func (m *MockIPostgresRepository) InsertSwipe(arg0 context.Context, arg1 *domain.Swipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSwipe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSwipe indicates an expected call of InsertSwipe.
func (mr *MockIPostgresRepositoryMockRecorder) InsertSwipe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSwipe", reflect.TypeOf((*MockIPostgresRepository)(nil).InsertSwipe), arg0, arg1)
}

// UpsertUser mocks base method.
func (m *MockIPostgresRepository) UpsertUser(arg0 context.Context, arg1 *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockIPostgresRepositoryMockRecorder) UpsertUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockIPostgresRepository)(nil).UpsertUser), arg0, arg1)
}

// MockIUserPostgresRepository is a mock of IUserPostgresRepository interface.
type MockIUserPostgresRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserPostgresRepositoryMockRecorder
}

// MockIUserPostgresRepositoryMockRecorder is the mock recorder for MockIUserPostgresRepository.
type MockIUserPostgresRepositoryMockRecorder struct {
	mock *MockIUserPostgresRepository
}

// NewMockIUserPostgresRepository creates a new mock instance.
func NewMockIUserPostgresRepository(ctrl *gomock.Controller) *MockIUserPostgresRepository {
	mock := &MockIUserPostgresRepository{ctrl: ctrl}
	mock.recorder = &MockIUserPostgresRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserPostgresRepository) EXPECT() *MockIUserPostgresRepositoryMockRecorder {
	return m.recorder
}

// GetUserDetail mocks base method.
func (m *MockIUserPostgresRepository) GetUserDetail(arg0 context.Context, arg1 *uint, arg2 *string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDetail indicates an expected call of GetUserDetail.
func (mr *MockIUserPostgresRepositoryMockRecorder) GetUserDetail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDetail", reflect.TypeOf((*MockIUserPostgresRepository)(nil).GetUserDetail), arg0, arg1, arg2)
}

// GetUserProfile mocks base method.
func (m *MockIUserPostgresRepository) GetUserProfile(arg0 context.Context, arg1 []uint) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", arg0, arg1)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockIUserPostgresRepositoryMockRecorder) GetUserProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockIUserPostgresRepository)(nil).GetUserProfile), arg0, arg1)
}

// UpsertUser mocks base method.
func (m *MockIUserPostgresRepository) UpsertUser(arg0 context.Context, arg1 *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockIUserPostgresRepositoryMockRecorder) UpsertUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockIUserPostgresRepository)(nil).UpsertUser), arg0, arg1)
}

// MockISwipePostgresRepository is a mock of ISwipePostgresRepository interface.
type MockISwipePostgresRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISwipePostgresRepositoryMockRecorder
}

// MockISwipePostgresRepositoryMockRecorder is the mock recorder for MockISwipePostgresRepository.
type MockISwipePostgresRepositoryMockRecorder struct {
	mock *MockISwipePostgresRepository
}

// NewMockISwipePostgresRepository creates a new mock instance.
func NewMockISwipePostgresRepository(ctrl *gomock.Controller) *MockISwipePostgresRepository {
	mock := &MockISwipePostgresRepository{ctrl: ctrl}
	mock.recorder = &MockISwipePostgresRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISwipePostgresRepository) EXPECT() *MockISwipePostgresRepositoryMockRecorder {
	return m.recorder
}

// GetSwipe mocks base method.
func (m *MockISwipePostgresRepository) GetSwipe(arg0 context.Context, arg1 uint, arg2 time.Time) ([]domain.Swipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwipe", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Swipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwipe indicates an expected call of GetSwipe.
func (mr *MockISwipePostgresRepositoryMockRecorder) GetSwipe(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwipe", reflect.TypeOf((*MockISwipePostgresRepository)(nil).GetSwipe), arg0, arg1, arg2)
}

// InsertSwipe mocks base method.
func (m *MockISwipePostgresRepository) InsertSwipe(arg0 context.Context, arg1 *domain.Swipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSwipe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSwipe indicates an expected call of InsertSwipe.
func (mr *MockISwipePostgresRepositoryMockRecorder) InsertSwipe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSwipe", reflect.TypeOf((*MockISwipePostgresRepository)(nil).InsertSwipe), arg0, arg1)
}

// MockIPurchasePostgresRepository is a mock of IPurchasePostgresRepository interface.
type MockIPurchasePostgresRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPurchasePostgresRepositoryMockRecorder
}

// MockIPurchasePostgresRepositoryMockRecorder is the mock recorder for MockIPurchasePostgresRepository.
type MockIPurchasePostgresRepositoryMockRecorder struct {
	mock *MockIPurchasePostgresRepository
}

// NewMockIPurchasePostgresRepository creates a new mock instance.
func NewMockIPurchasePostgresRepository(ctrl *gomock.Controller) *MockIPurchasePostgresRepository {
	mock := &MockIPurchasePostgresRepository{ctrl: ctrl}
	mock.recorder = &MockIPurchasePostgresRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPurchasePostgresRepository) EXPECT() *MockIPurchasePostgresRepositoryMockRecorder {
	return m.recorder
}

// InsertPurchase mocks base method.
func (m *MockIPurchasePostgresRepository) InsertPurchase(arg0 context.Context, arg1 *domain.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPurchase", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPurchase indicates an expected call of InsertPurchase.
func (mr *MockIPurchasePostgresRepositoryMockRecorder) InsertPurchase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPurchase", reflect.TypeOf((*MockIPurchasePostgresRepository)(nil).InsertPurchase), arg0, arg1)
}
