// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fahmialfareza/deals-dating-app-backend/internal/repository (interfaces: IRepository,IUserRepository,ISwiperRepository,IPurchaseRepository)

// Package mocks_repository is a generated GoMock package.
package mocks_repository

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/fahmialfareza/deals-dating-app-backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// CreatePurchase mocks base method.
func (m *MockIRepository) CreatePurchase(arg0 context.Context, arg1 *domain.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchase", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePurchase indicates an expected call of CreatePurchase.
func (mr *MockIRepositoryMockRecorder) CreatePurchase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchase", reflect.TypeOf((*MockIRepository)(nil).CreatePurchase), arg0, arg1)
}

// CreateSwipe mocks base method.
func (m *MockIRepository) CreateSwipe(arg0 context.Context, arg1 *domain.Swipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSwipe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSwipe indicates an expected call of CreateSwipe.
func (mr *MockIRepositoryMockRecorder) CreateSwipe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSwipe", reflect.TypeOf((*MockIRepository)(nil).CreateSwipe), arg0, arg1)
}

// GetSwipe mocks base method.
func (m *MockIRepository) GetSwipe(arg0 context.Context, arg1 uint, arg2 time.Time) ([]domain.Swipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwipe", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Swipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwipe indicates an expected call of GetSwipe.
func (mr *MockIRepositoryMockRecorder) GetSwipe(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwipe", reflect.TypeOf((*MockIRepository)(nil).GetSwipe), arg0, arg1, arg2)
}

// GetUserDetail mocks base method.
func (m *MockIRepository) GetUserDetail(arg0 context.Context, arg1 *uint, arg2 *string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDetail indicates an expected call of GetUserDetail.
func (mr *MockIRepositoryMockRecorder) GetUserDetail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDetail", reflect.TypeOf((*MockIRepository)(nil).GetUserDetail), arg0, arg1, arg2)
}

// GetUserProfile mocks base method.
func (m *MockIRepository) GetUserProfile(arg0 context.Context, arg1 []uint) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", arg0, arg1)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockIRepositoryMockRecorder) GetUserProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockIRepository)(nil).GetUserProfile), arg0, arg1)
}

// UpsertUser mocks base method.
func (m *MockIRepository) UpsertUser(arg0 context.Context, arg1 domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", arg0, arg1)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockIRepositoryMockRecorder) UpsertUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockIRepository)(nil).UpsertUser), arg0, arg1)
}

// MockIUserRepository is a mock of IUserRepository interface.
type MockIUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepositoryMockRecorder
}

// MockIUserRepositoryMockRecorder is the mock recorder for MockIUserRepository.
type MockIUserRepositoryMockRecorder struct {
	mock *MockIUserRepository
}

// NewMockIUserRepository creates a new mock instance.
func NewMockIUserRepository(ctrl *gomock.Controller) *MockIUserRepository {
	mock := &MockIUserRepository{ctrl: ctrl}
	mock.recorder = &MockIUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepository) EXPECT() *MockIUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserDetail mocks base method.
func (m *MockIUserRepository) GetUserDetail(arg0 context.Context, arg1 *uint, arg2 *string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDetail indicates an expected call of GetUserDetail.
func (mr *MockIUserRepositoryMockRecorder) GetUserDetail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDetail", reflect.TypeOf((*MockIUserRepository)(nil).GetUserDetail), arg0, arg1, arg2)
}

// GetUserProfile mocks base method.
func (m *MockIUserRepository) GetUserProfile(arg0 context.Context, arg1 []uint) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", arg0, arg1)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockIUserRepositoryMockRecorder) GetUserProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockIUserRepository)(nil).GetUserProfile), arg0, arg1)
}

// UpsertUser mocks base method.
func (m *MockIUserRepository) UpsertUser(arg0 context.Context, arg1 domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", arg0, arg1)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockIUserRepositoryMockRecorder) UpsertUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockIUserRepository)(nil).UpsertUser), arg0, arg1)
}

// MockISwiperRepository is a mock of ISwiperRepository interface.
type MockISwiperRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISwiperRepositoryMockRecorder
}

// MockISwiperRepositoryMockRecorder is the mock recorder for MockISwiperRepository.
type MockISwiperRepositoryMockRecorder struct {
	mock *MockISwiperRepository
}

// NewMockISwiperRepository creates a new mock instance.
func NewMockISwiperRepository(ctrl *gomock.Controller) *MockISwiperRepository {
	mock := &MockISwiperRepository{ctrl: ctrl}
	mock.recorder = &MockISwiperRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISwiperRepository) EXPECT() *MockISwiperRepositoryMockRecorder {
	return m.recorder
}

// CreateSwipe mocks base method.
func (m *MockISwiperRepository) CreateSwipe(arg0 context.Context, arg1 *domain.Swipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSwipe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSwipe indicates an expected call of CreateSwipe.
func (mr *MockISwiperRepositoryMockRecorder) CreateSwipe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSwipe", reflect.TypeOf((*MockISwiperRepository)(nil).CreateSwipe), arg0, arg1)
}

// GetSwipe mocks base method.
func (m *MockISwiperRepository) GetSwipe(arg0 context.Context, arg1 uint, arg2 time.Time) ([]domain.Swipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwipe", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Swipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwipe indicates an expected call of GetSwipe.
func (mr *MockISwiperRepositoryMockRecorder) GetSwipe(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwipe", reflect.TypeOf((*MockISwiperRepository)(nil).GetSwipe), arg0, arg1, arg2)
}

// MockIPurchaseRepository is a mock of IPurchaseRepository interface.
type MockIPurchaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPurchaseRepositoryMockRecorder
}

// MockIPurchaseRepositoryMockRecorder is the mock recorder for MockIPurchaseRepository.
type MockIPurchaseRepositoryMockRecorder struct {
	mock *MockIPurchaseRepository
}

// NewMockIPurchaseRepository creates a new mock instance.
func NewMockIPurchaseRepository(ctrl *gomock.Controller) *MockIPurchaseRepository {
	mock := &MockIPurchaseRepository{ctrl: ctrl}
	mock.recorder = &MockIPurchaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPurchaseRepository) EXPECT() *MockIPurchaseRepositoryMockRecorder {
	return m.recorder
}

// CreatePurchase mocks base method.
func (m *MockIPurchaseRepository) CreatePurchase(arg0 context.Context, arg1 *domain.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchase", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePurchase indicates an expected call of CreatePurchase.
func (mr *MockIPurchaseRepositoryMockRecorder) CreatePurchase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchase", reflect.TypeOf((*MockIPurchaseRepository)(nil).CreatePurchase), arg0, arg1)
}
