// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fahmialfareza/deals-dating-app-backend/internal/repository/redis (interfaces: IRedisRepository,IUserRedisRepository)

// Package mocks_redis_respository is a generated GoMock package.
package mocks_redis_respository

import (
	context "context"
	reflect "reflect"

	domain "github.com/fahmialfareza/deals-dating-app-backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockIRedisRepository is a mock of IRedisRepository interface.
type MockIRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRedisRepositoryMockRecorder
}

// MockIRedisRepositoryMockRecorder is the mock recorder for MockIRedisRepository.
type MockIRedisRepositoryMockRecorder struct {
	mock *MockIRedisRepository
}

// NewMockIRedisRepository creates a new mock instance.
func NewMockIRedisRepository(ctrl *gomock.Controller) *MockIRedisRepository {
	mock := &MockIRedisRepository{ctrl: ctrl}
	mock.recorder = &MockIRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRedisRepository) EXPECT() *MockIRedisRepositoryMockRecorder {
	return m.recorder
}

// DeleteUserDetail mocks base method.
func (m *MockIRedisRepository) DeleteUserDetail(arg0 context.Context, arg1 *uint, arg2 *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserDetail indicates an expected call of DeleteUserDetail.
func (mr *MockIRedisRepositoryMockRecorder) DeleteUserDetail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserDetail", reflect.TypeOf((*MockIRedisRepository)(nil).DeleteUserDetail), arg0, arg1, arg2)
}

// GetUserDetail mocks base method.
func (m *MockIRedisRepository) GetUserDetail(arg0 context.Context, arg1 *uint, arg2 *string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDetail indicates an expected call of GetUserDetail.
func (mr *MockIRedisRepositoryMockRecorder) GetUserDetail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDetail", reflect.TypeOf((*MockIRedisRepository)(nil).GetUserDetail), arg0, arg1, arg2)
}

// SetUserDetail mocks base method.
func (m *MockIRedisRepository) SetUserDetail(arg0 context.Context, arg1 *uint, arg2 *string, arg3 domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserDetail", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserDetail indicates an expected call of SetUserDetail.
func (mr *MockIRedisRepositoryMockRecorder) SetUserDetail(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserDetail", reflect.TypeOf((*MockIRedisRepository)(nil).SetUserDetail), arg0, arg1, arg2, arg3)
}

// MockIUserRedisRepository is a mock of IUserRedisRepository interface.
type MockIUserRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRedisRepositoryMockRecorder
}

// MockIUserRedisRepositoryMockRecorder is the mock recorder for MockIUserRedisRepository.
type MockIUserRedisRepositoryMockRecorder struct {
	mock *MockIUserRedisRepository
}

// NewMockIUserRedisRepository creates a new mock instance.
func NewMockIUserRedisRepository(ctrl *gomock.Controller) *MockIUserRedisRepository {
	mock := &MockIUserRedisRepository{ctrl: ctrl}
	mock.recorder = &MockIUserRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRedisRepository) EXPECT() *MockIUserRedisRepositoryMockRecorder {
	return m.recorder
}

// DeleteUserDetail mocks base method.
func (m *MockIUserRedisRepository) DeleteUserDetail(arg0 context.Context, arg1 *uint, arg2 *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserDetail indicates an expected call of DeleteUserDetail.
func (mr *MockIUserRedisRepositoryMockRecorder) DeleteUserDetail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserDetail", reflect.TypeOf((*MockIUserRedisRepository)(nil).DeleteUserDetail), arg0, arg1, arg2)
}

// GetUserDetail mocks base method.
func (m *MockIUserRedisRepository) GetUserDetail(arg0 context.Context, arg1 *uint, arg2 *string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDetail indicates an expected call of GetUserDetail.
func (mr *MockIUserRedisRepositoryMockRecorder) GetUserDetail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDetail", reflect.TypeOf((*MockIUserRedisRepository)(nil).GetUserDetail), arg0, arg1, arg2)
}

// SetUserDetail mocks base method.
func (m *MockIUserRedisRepository) SetUserDetail(arg0 context.Context, arg1 *uint, arg2 *string, arg3 domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserDetail", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserDetail indicates an expected call of SetUserDetail.
func (mr *MockIUserRedisRepositoryMockRecorder) SetUserDetail(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserDetail", reflect.TypeOf((*MockIUserRedisRepository)(nil).SetUserDetail), arg0, arg1, arg2, arg3)
}
